### ISSUE TITLE
OptionMissing using --help with a required option

### ISSUE THREAD

**Issue by edigiacomo** [rust-lang/getopts#46]
Sorry for my newbie question, but I can't find a way to exit without error when the `--help` flag is present and the `Options` object has a required option.

```rust
extern crate getopts;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut opts = getopts::Options::new();
    opts.optflag("h", "help", "print this help menu and exit");
    opts.reqopt("R", "required", "Required option", "VALUE");
    let matches = match opts.parse(&args[1..]) {
        Ok(m) => m,
        Err(f)  =>  {
            // myprogram --help
            println!("Error: {}", f);
            print!("{}", opts.usage("Usage: myprogram [options]"));
            std::process::exit(1);
        }
    };
    if matches.opt_present("h") {
        // myprogram --help --required VALUE
        print!("{}", opts.usage("Usage: myprogram [options]"));
        std::process::exit(0);
    }
    // myprogram --required VALUE
    println!("Running program");
}
```

**Comment by tromey** [comment]
I think the issue is that `--help` and perhaps `--version` have to be treated specially by getopts.  Otherwise, as you've found, required options don't really make sense, as they're required to make these special options work.

**Comment by prasannavl** [comment]
This issue seems to be quite old. While the community seems to have likely moved to clap.rs or docopt - I'm a big fan of the simplicity of `getopts`, and I almost always prefer this. 

That be said, one of the things I've found in my usages is that - it would be immensely helpful if the partial matches were passed along with the error. This helps examine it during the error. Would also make it simple enough to handle this particular scenario, as its becomes just another `opt_present` check during the error. I think this is a better approach as it retains the simplicity of the library without any special conditions as mentioned @tromey above.

**Comment by KodrAus** [comment]
It's been a couple years here and we've stopped most development to avoid any potential breakage in `rustc`. Since it doesn't look like we can make changes to the `Fail` type here without breakage we're probably going to have to accept this as a limitation of `getopts`.
